# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_player_friends_+', to='accounts.Player'),
        ),
    ]
