# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160314_1543'),
        ('api', '0003_auto_20160314_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives', models.ManyToManyField(related_name='alternatives', to='api.Song')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='api.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('whos_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whos_turn', to='accounts.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DurationField()),
                ('answered_correctly', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_player1', to='api.Score'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_player2', to='api.Score'),
        ),
    ]
