# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_uri', models.CharField(max_length=22)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='songs',
            field=models.ManyToManyField(to='songs.Song'),
        ),
    ]
