# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_status', models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=20)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='accounts.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives', models.ManyToManyField(related_name='alternatives', to='songs.Song')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='songs.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Category')),
                ('whos_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whos_turn', to='accounts.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DurationField()),
                ('answered_correctly', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_player1', to='quiz.Score'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_player2', to='quiz.Score'),
        ),
    ]
