# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160314_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Game'),
        ),
    ]
