# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20160314_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_player1', to='quiz.Score'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_player2', to='quiz.Score'),
        ),
    ]
