# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20160419_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score_player1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score_player2',
        ),
        migrations.AddField(
            model_name='round',
            name='player1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='player2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
