# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_overallscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='quiz.Game'),
        ),
    ]
