# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20160422_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallscore',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OverallScore',
        ),
    ]
